### ISSUE TITLE
Should fail gracefully if SHA of the previous release commit wasn't found

### ISSUE THREAD

**Issue by rreckonerr** [Exelord/ember-cli-deploy-sentry-cli#10]
While moving from `ember-cli-deploy-sentry` to your addon I've noticed that if `sentry-cli` is unable to find the previous release commit SHA it'll throw an error and break the build pipeline.

We're deploying from release branches and SHA will be lost after the branch is rebased, so it'd be nice if there was a workaround for that. Do you have any ideas?

### Log
```zsh
Error: Command failed: node_modules/.bin/sentry-cli  --auth-token XXX releases --org XXX --project XXX set-commits --auto XXX@XXX+XXX
error: Could not find the SHA of the previous release in the git history. Increase your git clone depth.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

### Steps to reproduce
1. Add a fixup commit
2. Deploy
3. Squash
4. Deploy

**Comment by Exelord** [comment]
Hi, thanks for reporting! I think that's sentry-cli issue, and we should look for solution right there :)

**Comment by rreckonerr** [comment]
Thanks for a quick reply!

I also think so, and they have an [open issue for that](https://github.com/getsentry/sentry-cli/issues/792).

The problem is that in the case of `ember-cli-deploy-sentry-cli` we're not able to opt-out of the Commits Assignment feature which will eventually break the build pipeline in my case. What I'm suggesting is to at least make it fail gracefully without deleting the release on "Could not find the SHA of the previous release in the git history. Increase your git clone depth." error.

**Comment by Exelord** [comment]
Hmm... Im not sure if we should do any error handling here. If the commit assignment failed, we want the whole release to fail, as something went wrong on the way. I think we should focus rather on fixing the command or raising it again as an issue to solve.

**Comment by rreckonerr** [comment]
Makes sense! 
Let's consider a situation when the previous release commit is **irreversibly** gone. Most likely if using the plain `sentry-cli` you'd just skip the `sentry-cli releases set-commits ...` part and proceed with creating a new release. But it's impossible to do it with this addon. I read through the set-commits documentation and couldn't find a way of "fixing" it.

**Comment by Exelord** [comment]
I think you woudn't skip the command as you dont know how it works internally (what it needs). So you will run it, get the error, and the omit. What in my opinion is a bug on their side, as the command should succeed in case no previous commit is found (which means no commits to assign - no work to do). And that could be achieved with additional option. I think this issue should be raised again.

**Comment by rreckonerr** [comment]
Seems like you also can archive releases that contain non-existing commits to deal with this:
https://github.com/getsentry/sentry-cli/issues/945#issuecomment-819532447
But this is not an option in my case since new app versions are adopted gradually during a long time span, so you can have multiple versions running in the wild simultaneously, and removing a release from sentry is not an option.

I've added a new issue in the sentry-cli repo, let's keep an eye on it https://github.com/getsentry/sentry-cli/issues/956

**Comment by rreckonerr** [comment]
Hi @Exelord!
There's a [new sentry-cli version](https://github.com/getsentry/sentry-cli/issues/956#issuecomment-848604711) that got released today. Now we can use `--ignore-missing` flag to prevent the cli tool from throwing an error in case a previous release commit wasn't found.

**Comment by Exelord** [comment]
Nice! you did it! Congrats! :) Of course. Could you create a PR?
