### ISSUE TITLE
Going Backwards in Version Number

### ISSUE THREAD

**Issue by alexlafroscia** [Exelord/ember-cli-deploy-sentry-cli#20]
It seems like the version number of `ember-cli-deploy-sentry-cli` has gone backwards?

<img width="711" alt="CleanShot 2021-10-28 at 11 09 07@2x" src="https://user-images.githubusercontent.com/1645881/139284326-0eccb71e-6314-47c8-998e-51dbfce7c3f9.png">

Your repo had `2.4.0` as the version number but npm has `3.0.0` as of yesterday. Now `2.5.0` is out, which I don't believe will be obvious as a newer version of the package than was available yesterday, since it's an _older_ version that the last thing on npm.

**Comment by Exelord** [comment]
Fixing it!!!! No idea how this happened😱

**Comment by alexlafroscia** [comment]
Thanks for the quick turn-out on this!
