### ISSUE TITLE
Native ember support by sentry

### ISSUE THREAD

**Issue by rreckonerr** [Exelord/ember-cli-deploy-sentry-cli#24]
Hi, @Exelord !
It seems like sentry finally has an [addon for ember](https://github.com/getsentry/sentry-javascript/tree/master/packages/ember). Do you think it's a valid replacement for this addon? 
Currently, I'm in process of migrating to 3.28 and I couldn't verify whether [@sentry/ember](https://www.npmjs.com/package/@sentry/ember) works for me.

**Comment by Exelord** [comment]
Hey :) Not exactly. That addon is for runtime integration of Sentry with Ember. `ember-cli-deploy-sentry-cli` is for deploy integration. It interacts with sentry-cli to create new versions and upload source maps. A bit different responsibility :) 

if you use ember-cli-deploy you can use both of them at the same time. The official one will enables the monitoring, while this one will integrate releases.

**Comment by rreckonerr** [comment]
Oh, sheesh! My bad!
I thought @sentry/ember is  also capable of integrating into the build pipeline. 

Thanks for a quick reply!
